### ISSUE TITLE
Add id, num_comics attributes to appropriate instance pages

### ISSUE THREAD

**Issue by Davis95** [cs373n/idb#126]
People can search a model, and then have the ID number to use for the API. Makes things easier for the user.

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add id, num_comics attributes to appropriate instance pages](https://trello.com/c/33ahXNV2/68-add-id-numcomics-attributes-to-appropriate-instance-pages)
