### ISSUE TITLE
Missing event for creator 9432

### ISSUE THREAD

**Issue by saketksingh** [cs373n/idb#137]
marveldb.net/creators/9432 .... the events array is empty, but on marvels API he has one event.

**Comment by saketksingh** [comment]
[332]  .. scraping issue in events_creators.  will require rescraping this relationship.

**Comment by saketksingh** [comment]
Rescraped

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Missing event for creator 9432](https://trello.com/c/b7RDrRw3/72-missing-event-for-creator-9432)
