### ISSUE TITLE
Add "Last Modified July 2017" to footer

### ISSUE THREAD

**Issue by saketksingh** [cs373n/idb#138]

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add "Last Modified July 2017" to footer](https://trello.com/c/sTLdg0eL/71-add-last-modified-july-2017-to-footer)

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add "Last Modified July 2017" to footer](https://trello.com/c/a4yEcIIJ/105-add-last-modified-july-2017-to-footer)
