### ISSUE TITLE
Fix contribution input when it gives empty string

### ISSUE THREAD

**Issue by dontforce** [cs373n/idb#139]

**Comment by Davis95** [comment]
When people type something, then delete it, we get an empty string instead of null. Implement logic to handle this.

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix contribution input when it gives empty string](https://trello.com/c/aEecc3Ks/104-fix-contribution-input-when-it-gives-empty-string)
