### ISSUE TITLE
Duplicate entries in character_comic table

### ISSUE THREAD

**Issue by cs373n** [cs373n/idb#161]
marveldb=# SELECT * FROM character_comic WHERE character_id=1011334;
 character_id | comic_id
--------------+----------
      1011334 |    22299
      1011334 |    21975
      1011334 |    21975
      1011334 |    21741
      1011334 |    21546
      1011334 |    24571
      1011334 |    21366
      1011334 |     8500
      1011334 |    10225
      1011334 |    10224
      1011334 |    10223
      1011334 |    10223
(12 rows)

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Duplicate entries in character_comic table](https://trello.com/c/xMre41nA/80-duplicate-entries-in-charactercomic-table)

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Duplicate entries in character_comic table](https://trello.com/c/f65pczSo/82-duplicate-entries-in-charactercomic-table)

**Comment by saketksingh** [comment]
perl -ne 'print unless $dup{$_}++;' input_file > output_file

**Comment by saketksingh** [comment]
removed dupes
