### ISSUE TITLE
Duplicate entries in the event_creators table

### ISSUE THREAD

**Issue by Davis95** [cs373n/idb#164]
When I tried to edit event 29, I tried to delete all creator associations. It comes back with a response saying that it should be deleting 107, but found like 124 of them or something, so the PATCH request fails.

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Duplicate entries in the event_creators table](https://trello.com/c/vLQxZe3e/106-duplicate-entries-in-the-eventcreators-table)
