### ISSUE TITLE
Fill in data for Characters model

### ISSUE THREAD

**Issue by saketksingh** [cs373n/idb#19]

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create page for character model](https://trello.com/c/Qkmex369/9-create-page-for-character-model)

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fill in data for Characters model](https://trello.com/c/9ZjoJ6eu/17-fill-in-data-for-characters-model)
