### ISSUE TITLE
Character attributes and comic data missing

### ISSUE THREAD

**Issue by deancarpenter17** [cs373n/idb#27]
Need to scrape data from Comic Vine API for character attributes and specific comic data.

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Character attributes and comic data missing](https://trello.com/c/cHT0GFNW/21-character-attributes-and-comic-data-missing)

**Comment by deancarpenter17** [comment]
Referenced Comic Vine API and added more character/comic attributes.
