### ISSUE TITLE
Install PostgreSQL and SQLAlchemy 

### ISSUE THREAD

**Issue by saketksingh** [cs373n/idb#39]
Install Flask-SQLAlchemy, PostgreSQL-9.4, psyscopg2, pgadmin4 and configure

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Install PostgreSQL and SQLAlchemy](https://trello.com/c/PY80qtwL/26-install-postgresql-and-sqlalchemy)

**Comment by saketksingh** [comment]
Installed all of the above
