### ISSUE TITLE
Inconsistent "num_x" attributes in JSON responses from db

### ISSUE THREAD

**Issue by deancarpenter17** [cs373n/idb#59]
The num_series, num_creators, etc. are showing incorrect values for the returned JSON responses. Found inconsistencies for: 
- [Series 3](http://52.201.212.202/api/series/3)
- [Creator 20](http://52.201.212.202/api/creator/20)
- [Series 45](http://52.201.212.202/api/series/45)

**Comment by deancarpenter17** [comment]
This is an issue with the official Marvel API that we scraped data from. Brainstorming workarounds.

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Inconsistent "num_x" attributes in JSON responses from db](https://trello.com/c/VsZgDh2L/33-inconsistent-numx-attributes-in-json-responses-from-db)

**Comment by deancarpenter17** [comment]
Need to check the array length of the actual arrays instead of relying on the "num_x" attributes on the instance pages, since they're completely incorrect in the official Marvel database. @Davis95 @saketksingh
