### ISSUE TITLE
Pagination causes network timeouts in browser console logs

### ISSUE THREAD

**Issue by deancarpenter17** [cs373n/idb#68]
Rapidly paginating through the character homepages causes the page to timeout.

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pagination causes network timeouts in browser console logs](https://trello.com/c/DIaFM8Hs/36-pagination-causes-network-timeouts-in-browser-console-logs)

**Comment by saketksingh** [comment]
Increased SQLAlchemy Pool Size

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [g](https://trello.com/c/iWPaxe21/44-g)
