### ISSUE TITLE
Search not re-rendering when attempting another search

### ISSUE THREAD

**Issue by deancarpenter17** [cs373n/idb#96]
When we've completed one search and then want to type another search, the API calls happen correctly, but the screen is not re-rendering. Need to look deeper into React lifecycle methods.

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [g](https://trello.com/c/Ctg83zM6/47-g)

**Comment by deancarpenter17** [comment]
In line 36 of SearchResults.js, had to set the 2nd parameter to updateSearchResults to null.
