### ISSUE TITLE
Filters not working correctly

### ISSUE THREAD

**Issue by deancarpenter17** [cs373n/idb#97]
Whenever we are using the Flask-Restless filter operations, "has", "any", "like", they are returning only exact matches, not context matches. Need to research these filter operations more.

**Comment by deancarpenter17** [comment]
Turns out you have to add "%" symbols before and after the keyword that you want to search for, in order to add context to that particular search term.

**Comment by cs373n** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [g](https://trello.com/c/cj4wUkf3/49-g)
